spring.application.name=TabletopReservations

spring.docker.compose.enabled=true

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
# Uncomment the following line (and remove the second) before the prod
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
